final List<Map<String, String>> financialAdvice = [
  {'title': 'Start Early', 'description': 'The sooner you start, the more time your money has to grow.'},
  {'title': 'Create a Budget', 'description': 'Track your income and expenses to find extra money for savings.'},
  {'title': 'Save Regularly', 'description': 'Make consistent contributions to your retirement fund.'},
  {'title': 'Take Advantage of Employer Matching', 'description': 'Contribute enough to get the full match.'},
  {'title': 'Open a Retirement Account', 'description': 'Utilize accounts like 401(k)s or IRAs.'},
  {'title': 'Maximize Contributions', 'description': 'Aim to contribute the maximum allowed.'},
  {'title': 'Automate Savings', 'description': 'Set up automatic transfers to your retirement account.'},
  {'title': 'Reduce Debt', 'description': 'Pay off high-interest debt to free up more money for savings.'},
  {'title': 'Diversify Investments', 'description': 'Spread your investments to manage risk.'},
  {'title': 'Increase Savings Rate', 'description': 'Gradually increase the percentage of your income you save.'},
  {'title': 'Reinvest Dividends', 'description': 'Use dividends to buy more shares instead of taking cash.'},
  {'title': 'Avoid Early Withdrawals', 'description': 'Keep your money invested for the long term.'},
  {'title': 'Take Advantage of Tax Breaks', 'description': 'Utilize tax-advantaged accounts.'},
  {'title': 'Monitor Your Investments', 'description': 'Regularly review and adjust your portfolio.'},
  {'title': 'Invest in Low-Cost Index Funds', 'description': 'Minimize fees and diversify easily.'},
  {'title': 'Delay Social Security', 'description': 'Waiting can increase your benefits.'},
  {'title': 'Consider a Roth IRA', 'description': 'Enjoy tax-free withdrawals in retirement.'},
  {'title': 'Stay Informed', 'description': 'Keep up with financial news and trends.'},
  {'title': 'Consult a Financial Advisor', 'description': 'Get professional advice tailored to your situation.'},
  {'title': 'Plan for Healthcare Costs', 'description': 'Save for medical expenses in retirement.'},
  {'title': 'Use Catch-Up Contributions', 'description': 'Take advantage of higher limits if you\'re over 50.'},
  {'title': 'Avoid Lifestyle Inflation', 'description': 'Keep expenses low as your income rises.'},
  {'title': 'Invest in Yourself', 'description': 'Education and skills can increase your earning potential.'},
  {'title': 'Avoid High Fees', 'description': 'Choose low-cost investment options.'},
  {'title': 'Keep an Emergency Fund', 'description': 'Prevent the need to dip into retirement savings.'},
  {'title': 'Set Specific Goals', 'description': 'Know how much you need to save and by when.'},
  {'title': 'Monitor Your Progress', 'description': 'Regularly check if you’re on track to meet your goals.'},
  {'title': 'Stay Disciplined', 'description': 'Stick to your savings plan even when it’s tough.'},
  {'title': 'Consider Part-Time Work', 'description': 'Supplement income during retirement.'},
  {'title': 'Downsize', 'description': 'Reduce living expenses by moving to a smaller home.'},
  {'title': 'Relocate', 'description': 'Consider moving to a more affordable area.'},
  {'title': 'Take Advantage of HSAs', 'description': 'Health Savings Accounts offer tax benefits.'},
  {'title': 'Use Windfalls Wisely', 'description': 'Save bonuses, tax refunds, or inheritances.'},
  {'title': 'Plan for Longevity', 'description': 'Ensure your savings last your lifetime.'},
  {'title': 'Stay Healthy', 'description': 'Lower healthcare costs by maintaining a healthy lifestyle.'},
  {'title': 'Protect Against Inflation', 'description': 'Choose investments that keep pace with inflation.'},
  {'title': 'Avoid Market Timing', 'description': 'Stick to a long-term investment strategy.'},
  {'title': 'Understand Your Pension', 'description': 'Know how much you’ll receive and when.'},
  {'title': 'Educate Yourself', 'description': 'Read books and take courses on personal finance.'},
  {'title': 'Network', 'description': 'Learn from others who are successfully saving for retirement.'},
  {'title': 'Consider Real Estate', 'description': 'Rental properties can provide income.'},
  {'title': 'Avoid Large Purchases', 'description': 'Limit big expenses that could deplete savings.'},
  {'title': 'Plan for Taxes', 'description': 'Understand how retirement income will be taxed.'},
  {'title': 'Stay Flexible', 'description': 'Be ready to adjust your plan as needed.'},
  {'title': 'Prioritize High-Interest Debt', 'description': 'Pay it off quickly to save more.'},
  {'title': 'Use Side Income', 'description': 'Funnel extra earnings into your retirement fund.'},
  {'title': 'Evaluate Insurance Needs', 'description': 'Ensure you have adequate coverage without overspending.'},
  {'title': 'Make Smart Consumer Choices', 'description': 'Buy quality items that last.'},
  {'title': 'Consider Annuities', 'description': 'They can provide steady income in retirement.'},
  {'title': 'Enjoy the Journey', 'description': 'Celebrate milestones and stay motivated.'},
];
